### ISSUE TITLE
ImportError: cannot import name addEmitters

### ISSUE THREAD

**Issue by catroot** [dieseldev/diesel#99]
from twiggy import log as olog, addEmitters, levels, outputs, formats, emitters
ImportError: cannot import name addEmitters

in file /usr/local/lib/python2.7/dist-packages/diesel/logmod.py

need to be changed to add_emitters to match logmod namespaces
works fine.

**Comment by mstrzele** [comment]
It's already been fixed in 75dc15e and released with 3.0.23. `pip` on Ubuntu installs old version (3.0.5).

**Comment by dowski** [comment]
Sorry about that. I'm apparently out of practice when it comes to PyPI. I uploaded a .zip of 3.0.24 to PyPI and it installs that version now.

@mstrzele thanks for the extra info and for pointing out a workaround.
